# Generated by Django 3.1.7 on 2022-02-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_servicenow_customer_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicenow',
            name='customer_password',
        ),
        migrations.RemoveField(
            model_name='servicenow',
            name='customer_user',
        ),
    ]
