# Generated by Django 3.1.7 on 2022-01-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_username', models.CharField(max_length=40)),
                ('twitter_user_id', models.CharField(max_length=40)),
                ('profile_image', models.CharField(max_length=200, null=True)),
                ('twitter_access', models.CharField(max_length=200, unique=True)),
                ('twitter_access_secret', models.CharField(max_length=200, unique=True)),
                ('subscription_id', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'twitter',
            },
        ),
    ]
