# Generated by Django 3.1.7 on 2022-02-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0002_twitter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter',
            old_name='twitter_access',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='twitter',
            old_name='twitter_access_secret',
            new_name='access_token_secret',
        ),
        migrations.RenameField(
            model_name='twitter',
            old_name='twitter_username',
            new_name='handle',
        ),
        migrations.RenameField(
            model_name='twitter',
            old_name='twitter_user_id',
            new_name='userid',
        ),
    ]
