# Generated by Django 4.1.2 on 2022-10-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='twitter_id',
            new_name='servicenow_username',
        ),
        migrations.AddField(
            model_name='customer',
            name='custom_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='customer',
            name='servicenow_password',
            field=models.CharField(default='pwd_2022', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='servicenow_sys_id',
            field=models.CharField(default='1234', max_length=100),
            preserve_default=False,
        ),
    ]
