# Generated by Django 4.1.2 on 2022-11-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='twitter_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='twitter_username',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
